### ISSUE TITLE
Compatibility with jQuery 3.2.1

### ISSUE THREAD

**Issue by RaquelPlaza** [wesnolte/Pajinate#57]
Pajinate does not work with jQuery 3.2.1, the following error comes up:
jquery-3.2.1.min.js:2 Uncaught TypeError: $items.size is not a function
According to jQuery, the method .size which was deprecated, has now being removed: https://api.jquery.com/size/

This makes the plugin not compatible with the latest jQuery version, any plans to update?

**Comment by darylsummers** [comment]
I second this! Your script is very useful for very simple tasks, any chance of an update to be compatible with the latest jQuery?

**Comment by AravindPrabash** [comment]
open the js file and replace `.size()` with `.length`. It works

**Comment by nexuzjaja** [comment]
JQuery 3 ready :D
